server:
  port: 80

# 连接池
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lancer?serverTimezone=Asia/Shanghai
    username: root
    password: ENC(zZPks3E8vdzd4yX+Zq1YoZPoK6l44MJy8T8R3ZgFsEFRvYWQhBCC3esxQ5x49KKS)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: ENC(3RFvUNXTlt4EF0as/IJ9P1kokOShYiRcsBlMZST88/I43jykUGMNIY6y7D/ii8V2)
      timeout: 500

# api文档
springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui

# 日志
logging:
  pattern:
    console: "Lancer - %green(%d{HH:mm:ss}) %red(%thread) %yellow(%-5level) %cyan(%logger{36}) - %msg %n"
  level:
    root: INFO
    # 记录sql
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
  file:
    name: /root/log/lancer.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
      max-history: 30

minio:
  endpoint: http://127.0.0.1:9000
  accesskey: admin
  secretkey: ENC(78aY1XV54RdQs2RJMPW1gdyzYAymlhp3BrgAULz2OjH5+nemK3OQAaqb3eXjw8J6)